#!/bin/sh

while getopts "v" opt; do
  case $opt in 
    v)
      echo "-v was triggered, for Verbose" >&2;
      find . -name .git -exec dirname {} ';' | xargs -L 1 -P 3 bash -c 'echo "$0" && cd "$0" && git pull && echo "\n"';
      exit 0;
      ;;
    \?)
      echo "Invalid Option: -$OPTARG" >&2
    ;;
  esac
done  

echo "Not Verbose"
find . -name .git -exec dirname {} ';' | xargs -L 1 -P 3 bash -c 'cd "$0" && git pull &>/dev/null'
